from pathlib import Path
from typing import Protocol, runtime_checkable

from eqo.domain.event import Event, EventType
from eqo.domain.memory import Memory, MemoryType
from eqo.domain.state import UserState
from eqo.domain.task import Task, TaskStatus
from eqo.domain.user import UserProfile


class TaskRepository(Protocol):
    """Porta de persistência usada pelo serviço de tarefas."""

    def add(self, task: Task) -> None: ...

    def save(self, task: Task) -> None: ...

    def get(self, task_id: str) -> Task | None: ...

    def list(self, status: TaskStatus | None = None) -> list[Task]: ...

    def remove(self, task_id: str) -> bool: ...


@runtime_checkable
class BackupRepository(Protocol):
    def backup_to(self, directory: str | Path) -> Path | None: ...


class UserStateRepository(Protocol):
    def get(self) -> UserState | None: ...

    def save(self, state: UserState) -> None: ...


class UserProfileRepository(Protocol):
    def get(self) -> UserProfile | None: ...

    def save(self, profile: UserProfile) -> None: ...


class MemoryRepository(Protocol):
    def upsert(self, memory: Memory) -> Memory: ...

    def get(self, memory_type: MemoryType, key: str) -> Memory | None: ...

    def list_memories(self, memory_type: MemoryType | None = None) -> list[Memory]: ...

    def search(self, query: str) -> list[Memory]: ...

    def delete(self, memory_type: MemoryType, key: str) -> bool: ...

    def purge_expired(self) -> int: ...


class EventRepository(Protocol):
    def add(self, event: Event) -> None: ...

    def list(self, event_type: EventType | None = None) -> list[Event]: ...

    def delete_type(self, event_type: EventType) -> int: ...
